### PR TITLE
chore: automate releases with Release-plz

### PR DESCRIPTION
**Pull request by hds**
Releasing the console crates has been a bit of a hassle. It requires
manual work run locally and as such, we have gone long periods without
releases, despite having changes which would be worth releasing.

[Release-plz] provides release automation based on GitHub actions. It
will create, and then update a PR for the next release.

Release-plz depends on [conventional commits] (which the `console`
project is already following) to determine the next version number for
each crate and then uses [cargo-semver-checks] to check that the version
bump is correct.

For the changelogs, [git-cliff] is used. Since we already started using
in #416, so we can reuse our existing `cliff.toml` config file. A small
change has been made to remove the footer, as it was getting included
multiple times in a single changelog file due to the delta updates.

**Caution**: In order to use Release-plz, a crates.io token first needs
to be added to the GitHub project. This means that anyone with PR merge
rights will be able to run a release by merging the Release PR.
Additionally, GitHub actions need to be given permission to create PRs.

The previous scripts used to release have been removed.

[Release-plz]: https://release-plz.ieni.dev/
[conventional commits]: https://www.conventionalcommits.org/en/v1.0.0/
[cargo-semver-checks]: https://github.com/obi1kenobi/cargo-semver-checks
[git-cliff]: https://git-cliff.org/

# Review Notes (DO NOT INCLUDE IN COMMIT MESSAGE)

To test the functionality of Release-plz, I copied `console` into a separate
project [hds_console] and played around with it there first.

The series of test PRs can be seen at: https://github.com/hds/hds_console/pulls?q=is%3Apr+is%3Aclosed

This released a series of test crates. The version history for each is:
- https://crates.io/crates/hds_console-api/versions
- https://crates.io/crates/hds_console-subscriber/versions
- https://crates.io/crates/hds_tokio-console/versions

The first release of each of the test crates was performed with the
existing release script. The subsequent releases were performed
by Release-Plz.

[hds_console]: https://github.com/hds/hds_console

### CODE REVIEW

**Comment by hds** [comment]
@hawkw What do you think about this workflow for releases? As mentioned, we will need to add a crates.io token to the action secrets on GitHub, but it would then allow releases entirely from here, no command line shenanigans needed (mostly).

**Comment by joshka** [comment]
This is the exact workflow (aside from the multiple package config) that I use for a bunch of tui related crates . It's fairly robust and works great. Being able to publish a release just by hitting merge on the release PR and trusting that everything is just handled correctly is an excellent workflow.

**Review by 0xPoe — APPROVED** [review]
Looks good to me. Thanks! 👍

Thanks for testing it with your own repo.

**Review by hawkw — APPROVED** [review]
This looks great, thanks for working on this!

It might be nice to add some documentation to `CONTRIBUTING.md` (or something) explaining the new release workflow and how to trigger a release, but it's fine to add that in a separate PR.

Do we need to export a cargo registry token secret in the repo settings for the release-plz action to use? I can go do that.

**Pull request merged**
