### PR TITLE
feat(console): Add vi style keybinds for navigating tables

### PR DESCRIPTION
**Pull request by k0nserv**
Adds `hjkl` as alternatives to the arrow keys and `G` and `gg` to navigate
to the first and last rows in tables, respectively.

Changes to the UI:

image

### CODE REVIEW

**Review by hawkw — COMMENTED** [review]
nice, i'm sure this will make a lot of people very happy! :)

we also display the keybindings in the UI, so maybe we should also add the vi-style keybindings to the table controls we display, here:
https://github.com/tokio-rs/console/blob/1aa9b594f30e42098c6c6bbf41eb1d2b01dc0426/console/src/view/table.rs#L162-L176

also, I wonder if it's worth making a CLI option for toggling between vi only, arrow keys only, and enabling both? but, we could also do that in a follow-up PR.

**Comment by k0nserv** [comment]
Thanks for the suggestions, I considered both those options as I wrote this. 

For adding the bindings to the UI I wasn't sure how to do it so I wanted to raise it here instead.

One possibility is `\u{2190}(h)\u{2192}(l)` for left/right and likewise for up and down. I'm happy to add this, my concern was that it might be a bit messy. I guess for `G` and `gg` those could just be added directly.

e.g. like this
image


An option to consider if this display of keybinding does get too unwieldy is `?` to bring up a floating window that displays them all.

About the CLI toggling: My thinking was there's no harm in having both by default, folks will use the ones they know/prefer? I'm not sure there's any benefit to allowing them to be disabled, but I can certainly add that in a follow up PR if you wish

**Comment by hawkw** [comment]
> One possibility is `\u{2190}(h)\u{2192}(l)` for left/right and likewise for up and down. 

How about `\u{2190}/\u{2192} or h/l` and similar, instead? (ideally, with the `or` and the slashes not bolded). But, honestly, I'm fine with whatever. I think just displaying `gg` and `G` separately the way you did in your screenshot looks correct.

> An option to consider if this display of keybinding does get too unwieldy is `?` to bring up a floating window that displays them all.

Yeah, that might be a good idea, especially if we add more controls for things like filtering (#131) in the future. A simpler solution might just be to make it two lines rather than one line, but that eats up more vertical real estate...

> About the CLI toggling: My thinking was there's no harm in having both by default, folks will use the ones they know/prefer? I'm not sure there's any benefit to allowing them to be disabled, but I can certainly add that in a follow up PR if you wish

Honestly, the only real benefit I had in mind is that it makes the controls list shorter to disable one set of keybindings :) I really don't think people are likely to disable or enable keybindings with a command-line option. I think that if we eventually add a _config file_, it might be more likely to want to configure keybindings there, but in that case, I'd imagine users would want to specify custom keybindings, rather than just turning them on or off. All of that is just something to think about for the future, though.

Once we've added the vi keybindings to the table controls, I'll be happy to merge this!

**Comment by k0nserv** [comment]
image


Here's what it looks like now

**Comment by hawkw** [comment]
> image
> 
> Here's what it looks like now

Yup, that looks good to me.  I noticed that the controls line is now quite long, and probably won't fit in a narrower terminal...and that we truncate the line instead of wrapping it. So, I went ahead and implemented wrapping in PR #231, so that we can add more text to the controls and still have it display nicely on narrower terminals. Once that's merged, let's go ahead and merge this PR!

**Comment by hawkw** [comment]
@k0nserv any updates here? It would be nice to get this updated with the latest `main` branch, and then I'll be happy to merge it!

**Comment by k0nserv** [comment]
I saw that you had merged main into this branch and I thought you'd merge when #231 was merged. 

What do you need me to do before we can merge?

**Comment by hawkw** [comment]
> What do you need me to do before we can merge?

It looks like the change for adding the keybindings to the help text hasn't actually been added to this branch yet? Once that's done, I'll merge this.

**Comment by k0nserv** [comment]
Huh, I thought I pushed that, but I guess not then. Shall resolve

**Comment by k0nserv** [comment]
Rebased on `main` and pushed now

**Comment by k0nserv** [comment]
I believe you need to approve the some of the workflows for them to run

image

**Review by hawkw — APPROVED** [review]
okay, looks good to me! thanks again for working on this!

**Comment by k0nserv** [comment]
Thanks for merging :+1:

**Pull request merged**
