### PR TITLE
fix(console): don't crash if `COLORTERM`/`LANG` is not set

### PR DESCRIPTION
**Pull request by hawkw**
Currently, the console CLI/env var handling code _requires_ the
`COLORTERM` env variable. This isn't correct, as some terminals may not
set it. In that case, we should assume the terminal isn't advertising
24-bit color support, rather than crashing.

Currently, this happens if I unset the env variable:

```console
$ unset COLORTERM

$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
     Running `target/debug/console`
error: The following required arguments were not provided:
    --colorterm <truecolor>

USAGE:
    console [FLAGS] [OPTIONS] --lang <LANG> --colorterm <truecolor> [TARGET_ADDR]

```

After this branch, if I unset `COLORTERM`, the console just runs without
colors.

Similarly, the `LANG` environment variable is no longer required, either.
If it's unset, we'll default to `en_us.UTF-8`. Possibly, we should *really*
be falling back to ASCII if `$LANG` is not set, but _most_ terminals really
ought to support UTF-8...

Finally, this fixes a bug in the way we parse `tput colors` output. The output
ends in a newline, but our parsing code doesn't handle whitespace...so we 
will currently always assume no colors are supported if we fall back to `tput`.
This branch adds a `trim` call.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Just an anecdote from my environment, even though the variable isn't set, manually passing `--colorterm truecolor` works just fine, and `tput colors` returns 256. If the env var is missing, could we default to some sort of "auto"?

**Comment by hawkw** [comment]
>  If the env var is missing, could we default to some sort of "auto"?

If the env var is missing, we will check `tput colors` next (which is essentially "auto"). There may be more ways to detect color support that we should also try --- we could potentially also look at `$TERM` and see if the terminal program is in a list of terminals we know support colors regardless of what `tput` says.

I'm a little hesitant to default to emitting color escapes if we don't have _some_ way of positively determining that they'll work --- I don't want to give users whose terminals don't support colors, or don't support 24-bit millions of colors, a big pile of gibberish by default.

**Comment by hawkw** [comment]
Also, I've updated this branch to also handle the `$LANG` variable not being set.

**Comment by seanmonstar** [comment]
Oh yea, by "auto" I meant check `tput` or something. Sounds good!

**Review by seanmonstar — APPROVED** [review]

**Pull request merged**
